### PR TITLE
UTF-8 output support

### PR DESCRIPTION
**Pull request by Jojodicus**
It seems like output for UTF-8 is broken, adding the line in the commit fixes it for my systems.

I know this project is quite old, but I've just recently found and love it. It boggles my mind that there is still no simpler free solution, even after all those years...

### CODE REVIEW

**Comment by davorg** [comment]
Thank for for reminding me of the existence of this old project. Maybe I'll give it a little more love, now that I know there's someone out there who finds it useful :-)

**Comment by davorg** [comment]
Oh, that's weird. I use `-CS` on the shebang line. And that's supposed to do the same thing. From [perlrun](https://perldoc.perl.org/perlrun):

> **-C [number/list]**
> The **-C** flag controls some of the Perl Unicode features.
> 
> As of 5.8.1, the **-C** can be followed either by a number or a list of option letters. The letters, their numeric values, and effects are as follows; listing the letters is equal to summing the numbers.
> 
> `I     1   STDIN is assumed to be in UTF-8`    
> `O     2   STDOUT will be in UTF-8`    
> `E     4   STDERR will be in UTF-8`    
> `S     7   I + O + E`

I shall investigate further. Thanks for giving me a mystery to solve :-)

**Comment by Jojodicus** [comment]
Hm, that is indeed weird. It also doesn't work for me when running via `perl -CS` manually, but experimenting some more, `perl -CSD` seems to work just fine. Maybe that's a better way of doing it, I'm not a perl guy to be honest
My perl version is 5.38.1 if that is of any help

**Comment by davorg** [comment]
Yeah, that's useful information, thanks.

**Pull request merged**
